# Automatic analysis reads this file. sonar-project.properties is ignored by autoscan.
# See https://docs.sonarsource.com/sonarqube-cloud/analyzing-source-code/automatic-analysis
sonar.sources=src,entrypoints
sonar.tests=src,e2e
sonar.exclusions=src/components/ui/**,src/tests/**,**/*.test.ts,**/*.test.tsx
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,e2e/**/*.e2e.ts,src/tests/**
sonar.sourceEncoding=UTF-8
