sonar.projectKey=d0whc3r_statsig-browser-extension
sonar.organization=d0whc3r

sonar.sources=src,entrypoints
sonar.tests=src,e2e

sonar.exclusions=**/*.d.ts,**/node_modules/**,.output/**,coverage/**,jscpd-report/**,test-results/**,playwright-report/**,dist/**,public/**,src/components/ui/**,src/tests/**,**/*.test.ts,**/*.test.tsx,**/pnpm-lock.yaml
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,e2e/**/*.e2e.ts,src/tests/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,e2e/**,src/tests/**,src/components/ui/**,**/*.d.ts,entrypoints/**

sonar.sourceEncoding=UTF-8
